---
name: XYZ_By_DarkSidesYT
main: darksidesyt\XYZ
author: DarkSidesYT
description: XYZ simple
version: 1.0.0
api:
- 3.0.0
commands:
  xyz:
    description: Voir vos coordonnées en temps réel
    permission: use.xyz
    usage: /xyz
permissions:
  livexyz:
    default: true
    description: Autorisé l'utilisation de la commande
...
