---
## Nombre de tick avant de refresh
refreshRate: 4
## Mode de l'affichage (tip/popup)
displayMode: "tip"
## Ajouté l'erreur donné si la personne n'a pas la permission (use.xyz)
permissionError: Vous n'avez pas la permission !
...
